// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awelvjmovwauiccchadg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3ZWx2am1vdndhdWljY2NoYWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzk0MjAsImV4cCI6MjA2NDcxNTQyMH0.Rvx3uRyv46tf_721sw088LBR8MiHSwVdxI4f0QjtzvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);